insightsengineering/r.pkg.template

.github/workflows/bioccheck.yaml
https://github.com/insightsengineering/hermes/pull/156#discussion_r754362713
=> Add no-check-version-num param to bioccheck

.github/workflows/pkgdown.yaml
Fixes https://github.com/insightsengineering/automation-tasks/issues/169
=> fix use of commit owner and force branch use

.github/workflows/validation.yaml
https://github.com/insightsengineering/automation-tasks/issues/162
=> Add theValidatoR action

.github/workflows/validation.yaml
Related to https://github.com/insightsengineering/ggplot2.utils/runs/4333529865?check_suite_focus=true#step:4:748
https://github.com/insightsengineering/automation-tasks/issues/162
=> Fix error with missing dependencies

.github/workflows/licenses.yaml
=> Generate license report

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .lintr
Additional image, i.e. R 4.1.2 + BioC 3.14 for `R CMD *` checks. There is no hard requirement for this to pass for consumer repos.
=> Enable R 4.1.2+BioC 3.14 checks

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml
Add a workflow option to install sysdeps.
=> Add option to install sysdeps

.github/workflows/linter.yaml, .lintr, R/hello.R
Fail lintr on error via an env var set in SuperLinter.
=> Fail linter on error

.github/workflows/roxygen.yaml
Fixes https://github.com/insightsengineering/automation-tasks/issues/172
test action details: 
https://github.com/insightsengineering/test.nest/actions/runs/1563773859
=> 172 automation - roxygen check - fail build on warning

.github/workflows/short-tagging.yml
https://github.com/insightsengineering/idr-tasks/issues/181
=> 181 semver gh action

.github/workflows/short-tagging.yml
=> ubuntu-latest

.github/CODEOWNERS, .github/workflows/test-coverage.yaml
Use the Insights Engineering Code Coverage Action as a replacement.
=> Use IE coverage action

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml
Add a workflow-call control parameter for staged deps check.
=> Add controls for staged deps checks

.github/workflows/version-bump.yaml
Add release candidate version bumps.
=> Add release candidate version bump

.github/workflows/validation.yaml
fix https://github.com/insightsengineering/idr-tasks/issues/211
=> Update validator action version and turn off dev deps installation

.github/workflows/pkgdown.yaml
Change multiversion pkgdown repo name.
=> Change multiversion pkgdown repo name

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml, README.md
Test action skips and add the style check workflow.
=> Update workflow skippers, nd add style check workflow

.github/workflows/gitleaks.yaml
Change threshold and output type.
=> Add threshold and change output type

.github/workflows/gitleaks.yaml, .github/workflows/style.yaml, R/hello.R, tests/testthat/test-api.R
Also implicitly test PII check performance.
=> Styler optimization

.github/workflows/gitleaks.yaml
Only run PII checks for changed files.
=> Run PII checks only for changed files

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/short-tagging.yml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml
For the time being. Revert back to `ubuntu-latest` when quota resets.
=> Try self-hosted runners

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/short-tagging.yml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml
Reverts insightsengineering/r.pkg.template#60
=> Back to ubuntu-latest

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/short-tagging.yml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml
- Do not run workflows on draft PR
- Cancel previous workflow runs for a given commit or PR
=> Additional optimizations

.github/workflows/gitleaks.yaml
Issue:
Checking .svg, Rd git files
https://github.com/insightsengineering/teal.widgets/runs/5462808447?check_suite_focus=true#step:3:752
Test:
https://github.com/insightsengineering/teal.widgets/runs/5463258506?check_suite_focus=true
=> presidio ignore

.github/workflows/gitleaks.yaml
Test on https://github.com/insightsengineering/teal.slice/pull/7 -> pass as expected
=> adding jpg

.github/workflows/style.yaml, R/hello.R
Change remediation message for the styler workflow
=> Change phrasing for styler workflow error

.github/workflows/gitleaks.yaml
Test on https://github.com/insightsengineering/dm.filter.labels/pull/21
=> adding rda

.github/workflows/validation.yaml
Not so fast. This is incorrect @tomszosz
=> Revert "new name of r-pkg-validation job"

.github/workflows/test-coverage.yaml
=> check coverage with covtrace

LICENSE
closes https://github.com/insightsengineering/coredev-tasks/issues/234
=> update company name

.github/workflows/linter.yaml, .pre-commit-config.yaml, README.md
Override the non-restrictive markdown lint config.
=> Override SuperLinter configs

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version.yaml
=> Add PR types

.github/workflows/pkgdown.yaml, .github/workflows/test-coverage.yaml
Otherwise it complains of pkgdown not being available.
=> Handle renv lockfiles

.github/workflows/style.yaml
v1.7.0 contains fixes that were critical for our use.
=> Install styler from CRAN

.github/workflows/build-check-install.yaml, DESCRIPTION
[Issue](https://github.com/insightsengineering/idr-tasks/issues/266)
- [printing detected notes and failing afterwards](https://github.com/insightsengineering/scda.2022/runs/6857821280?check_suite_focus=true#step:13:43)
=> 266 Fail PR on R CMD CHECK notes (but not all)

.github/workflows/pkgdown.yaml
The old one wasn't working, so the new one got a facelift.
=> Use updated multi-version docs

.github/workflows/roxygen.yaml
=> Feature to auto-update man pages

.github/workflows/build-check-install.yaml
Add generic option for extra R CMD check flags
=> Option to add additional R CMD check params

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .gitignore
Adds Grammar checks and caching for staged dependencies.
=> Grammar annotations and SD cache

.github/workflows/build-check-install.yaml, .github/workflows/links.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml
=> Update coverage action

.github/workflows/grammar.yaml, .github/workflows/version-bump.yaml, DESCRIPTION
- Grammar checks are now their own workflow so that it's an opt-in feature
- Version bumps will now include date updates if the Date field exists in the DESCRIPTION file
=> Dedicated Grammar Workflow and Date Updater

.lintr, README.md, inst/WORDLIST
=> linters_with_defaults

.Rbuildignore, .github/workflows/build-check-install.yaml, tests/testthat.R
And also remove the `Remotes` field from the package build.
=> Update testing strategy

.github/workflows/build-check-install.yaml
=> if testthat

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml
=> Test new SD version

.github/workflows/build-check-install.yaml
Provide the ability to export additional env vars to the R CMD check action.
=> Add simple dotenv exporter

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml
=> Handle checkouts from forks

.github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml
Add dotenv options for other workflows
=> More dotenv

.github/workflows/build-check-install.yaml
Don't show tables without differences between test suites or test cases.
This PR depends on https://github.com/insightsengineering/junit-xml-diff/pull/4
=> Don't report empty tables

.github/workflows/build-check-install.yaml
Fixes an issue seen e.g. [here](https://github.com/insightsengineering/teal.code/pull/106#issuecomment-1420735993).
=> Add missing newline

.github/workflows/style.yaml
Fixes [this bug](https://github.com/insightsengineering/teal.goshawk/actions/runs/4171856369/jobs/7222465461).
=> Styler fix

.github/workflows/version-bump.yaml
* [Workflow run](https://github.com/walkowif/tern/actions/runs/4253138517/jobs/7397610763)
* [Resulting commit](https://github.com/walkowif/tern/commit/83c5a05455729b5e3a65f73b5339f798426d6579)
=> Precommit autoupdate

.github/workflows/cran-status.yaml
Part of https://github.com/insightsengineering/idr-tasks/issues/528
I have fixed some corner cases in the original workflow [here](https://github.com/pharmaverse/admiralci/blob/main/.github/workflows/cran-status.yml).
=> Add CRAN status workflow

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/verdepcheck.yaml, .github/workflows/version-bump.yaml
Use `REPO_GITHUB_TOKEN` in case it's set. Otherwise use `GITHUB_TOKEN` where required.
=> Use proper GitHub token

.github/workflows/verdepcheck.yaml
upload additional artifact for debugging
already added in script here: https://github.com/insightsengineering/r-verdepcheck-action/blob/f9b9efa9f3082411e7343ddbf50f4ac48836af2a/script.R#L33
=> upload additional artifact

.github/workflows/grammar.yaml
Solves the issue from [here](https://github.com/insightsengineering/tlg-catalog/actions/runs/5574388333/jobs/10182938353).
=> Update changed files action

.github/workflows/build-check-install.yaml
Fix a bug in `build-check-install` workflow, occurring for example [here](https://github.com/insightsengineering/helios/actions/runs/5572946323/jobs/10182027132).
=> Fix release workflow

.github/workflows/build-check-install.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/614
=> Show R CMD check logs

.github/workflows/linter.yaml
=> Upgrade to SuperLinter v5

.github/workflows/version-bump.yaml
Fix issue with `.pre-commit-config.yaml` file
=> Fix vbump v2

.github/workflows/links.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/661.
=> Add urlchecker

.github/workflows/wasm.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/785.
=> Workflow for adding WASM packages to GitHub release
