insightsengineering/r.pkg.template

.github/workflows/validation.yaml
Fix https://github.com/insightsengineering/r.pkg.template/runs/4325548352?check_suite_focus=true#step:6:23 (action need to run on bare ubuntu-latest os not docker image)
related to:
https://github.com/insightsengineering/automation-tasks/issues/162
=> Decouple push artifact to release to fix error

.github/workflows/licenses.yaml
Use v1, which points to the latest version of the license report check.
=> Use v1 of license report check

.github/workflows/pkgdown.yaml
If readme.md has images, then `pkgdown` will produce warning message and Github action for `Pkgdown Docs` will fail.
This error is only for rocker 4.1.2 with `pkgdown` ver.2.0.1.
Prev. ver. is (pkgdown 1.6/rocker_4.1.0) is ok.
For now, we are ignoring these warnings.
=> ignore warning on pkgdown

.github/workflows/version-bump.yaml
https://github.com/insightsengineering/idr-tasks/issues/207
backgroud:
```
> desc::desc_bump_version(5)
Package version bumped from ‘0.10.0.9056’ to ‘0.10.0.9056.1’
....
```
```
> desc::desc_bump_version("dev")
Package version bumped from ‘0.10.0.9056.1’ to ‘0.10.0.9057.0’
```
Remove latest part -> `0.10.0.9057`
=> Remove .0 on the end of version

.github/workflows/validation.yaml
https://github.com/insightsengineering/idr-tasks/issues/211
It's needed to set authentycatoin. Dependencies has `update="never"`, so not updating any existing packages. Tested `teal.modules.clinical` and `tern` and looks like it's solves issue with git2r
=> Update validator to install dev deps with no update

.github/workflows/version-bump.yaml
fixes error observed for `".10"`
```
> gsub(".0$", "", "1.2.3.4.10" )
[1] "1.2.3.4."       # <- incorrect version number
> gsub("[.]0$", "", "1.2.3.4.10" )
[1] "1.2.3.4.10"
> gsub("[.]0$", "", "1.2.3.4.0" )
[1] "1.2.3.4"
```
=> escape a dot

.github/workflows/build-check-install.yaml, .github/workflows/validation.yaml
The `workflow_call` input will be blank by default. Override the value.
=> Fix failing check because of unset env var

.github/workflows/test-coverage.yaml
Add verbose coverage error reporting in cases where coverage reports fail, and the output of the results are embedded elsewhere.
=> Verbose coverage error reporting

.github/workflows/validation.yaml
Fixes #269
```
there is an error
[Invalid workflow file: .github/workflows/validation.yaml#L74](https://github.com/insightsengineering/r.pkg.template/actions/runs/2153379295/workflow)
The workflow is not valid. .github/workflows/validation.yaml (Line: 74, Col: 12): Job 'upload-release-assets' depends on unknown job 'r-pkg-validation'.
```
https://github.com/insightsengineering/r.pkg.template/actions/runs/2153379295
=> new name of r-pkg-validation job

.github/workflows/test-coverage.yaml, .github/workflows/validation.yaml
The job name has changed for the validation job, and also add an option to enable the covtracer job as workflow-level flag.
=> Fix job name and optionally run covtracer

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml
=> Performance and devX optimizations

.github/workflows/release.yaml
The `generate_release_notes` parameter of `softprops/action-gh-release` allows to utilize GitHub-generated release notes, and to extend the existing release description with additional details, like the list of merged PRs, and the list of contributors to the release.
This part of release notes can be further customized with [`.github/release.yml` file](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration).
[Example of extended release notes](https://github.com/walkowif/tern/releases/tag/v1.0.6) without any additional configuration.
=> Add GitHub-generated release notes to release description

.github/workflows/release.yaml, .github/workflows/version-bump.yaml
Changes to:
* `release.yaml` - it's necessary to enable using custom (`insightsengineering`) PAT in order to create the GitHub release. The reason is: when using `GITHUB_TOKEN`, the creation of release will not trigger any workflows in order to avoid recursive invocations of workflows.
* `version-bump.yaml` - when a new `vbump-after-release` input is specified, package version will be bumped, and a new section in `NEWS.md` will be created.
=> Auto-update dev package version after release is created

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/grammar.yaml, .github/workflows/licenses.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml
Add `package-subdirectory` input to selected workflows to allow running the workflows for repositories where R packages are stored in a subdirectory within the repository.
=> Add package subdirectory input

.github/workflows/spelling.yaml, .github/workflows/version-bump.yaml
[Example workflow run removing redundant entries from WORDLIST](https://github.com/walkowif/tern/actions/runs/5729135507/job/15525243131)
[Example commit with entries removed from WORDLIST](https://github.com/walkowif/tern/commit/c5ee9129f59806fdc174f37f537f75786917c10e)
This will require the propagation of removal of [this line](https://github.com/insightsengineering/tern/blob/main/.github/workflows/check.yaml#L66) from repositories where this functionality is supposed to be enabled.
This way the workflow will be configured to remove redundant WORDLIST entries on `main` only.
=> Wordlist reduction

.github/workflows/pkgdown.yaml
https://github.com/insightsengineering/idr-tasks/issues/629
=> Custom pkgdown publishing

.github/workflows/spelling.yaml
PR created to address the following errors when `spelling` workflow is run on `main`:
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request. Required status check "R CMD Check 🧬 / ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17, version latest" is expected.        
To https://github.com/insightsengineering/rlistings
! [remote rejected] main -> main (protected branch hook declined)
```
```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.        
To https://github.com/insightsengineering/random.cdisc.data
! [remote rejected] main -> main (protected branch hook declined)
```
=> Use token in spelling workflow

.github/workflows/verdepcheck.yaml
WIP :: parent issue: https://github.com/insightsengineering/nestdevs-tasks/issues/7
This PR depends on some upstream changes that need to be finalized before being ready to review.
* https://github.com/insightsengineering/verdepcheck/pull/24
* https://github.com/insightsengineering/verdepcheck/pull/26
* https://github.com/insightsengineering/r-verdepcheck-action/pull/16
* Documentation update on strategy, replacing `min` with `min_isolate` and `min_cohort`
=> Update strategies on R min deps check workflow

.github/workflows/build-check-install.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/660
Fix an error when the upload of tar.gz package to GitHub release fails.
This was caused by the use of git tag version instead of version from DESCRIPTION.
=> Fix package version for rc tags

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/branch-cleanup.yaml, .github/workflows/build-check-install.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/verdepcheck.yaml
https://github.com/insightsengineering/idr-tasks/issues/676
=> Update status checks to use latest image

.github/workflows/build-check-install.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml
Make sure that commits are successfully added to the PR branch by both style and roxygen workflows, and that any such commits also retrigger the whole check workflow.
=> Style and roxygen workflow improvements

.github/workflows/build-check-install.yaml
Add concurrency group input to allow multiple simultaneous instances of R CMD check workflow in a calling workflow (utilized e.g. in TLG Catalog).
=> Add concurrency group input to R CMD check workflow

.github/workflows/build-check-install.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/767.
=> Update packages in `build-check-install` workflow + run `staged.dependencies` conditionally

.github/workflows/audit.yaml, .github/workflows/bioccheck.yaml, .github/workflows/branch-cleanup.yaml, .github/workflows/build-check-install.yaml, .github/workflows/gitleaks.yaml, .github/workflows/grammar.yaml, .github/workflows/licenses.yaml, .github/workflows/links.yaml, .github/workflows/linter.yaml, .github/workflows/pkgdown.yaml, .github/workflows/release.yaml, .github/workflows/roxygen.yaml, .github/workflows/spelling.yaml, .github/workflows/style.yaml, .github/workflows/test-coverage.yaml, .github/workflows/validation.yaml, .github/workflows/verdepcheck.yaml, .github/workflows/version-bump.yaml, .github/workflows/version.yaml
[Changes between `actions/checkout@v4.1.1` and `actions/checkout@v4.1.3`](https://github.com/actions/checkout/compare/v4.1.1...v4.1.3) (probably related to sparse checkout) introduced a regression in workflows which use `staged.dependencies`.
The following error occurs in the `Run Staged dependencies` step:
```
Error in git2r::repository(".") : Unable to open repository at 'path'
Calls: <Anonymous> -> <Anonymous>
Execution halted
```
=> Use older version of `actions/checkout`

.github/workflows/revdepcheck.yaml
https://github.com/insightsengineering/idr-tasks/issues/712
=> Initialize revdepcheck action

.github/workflows/verdepcheck.yaml
Closes https://github.com/insightsengineering/idr-tasks/issues/776.
=> Add cache to verdepcheck workflow

.github/workflows/links.yaml
`parallel = FALSE` seems to help (for reasons unknown) with errors like `502 Bad Gateway` for https://pharmaverse.slack.com.
=> Fix urlchecker

.github/workflows/rhub.yaml
To prevent GitHub rate-limiting errors during dependency installation in the R-hub workflow.
=> Pass REPO_GITHUB_TOKEN to R-hub workflow

.github/workflows/rhub.yaml
- remove steps labels for consistency
- lint
=> remove steps labels for consistency; lint

.github/workflows/rhub.yaml
Disable `linux (R-devel)` R-hub check because of unexplained timeouts in `setup-r-dependencies` step `Modify DESCRIPTION file (development)`.
=> fix: disable linux r-hub check

.github/workflows/revdepcheck.yaml
test those two together:
- https://github.com/insightsengineering/r.pkg.template/pull/255
- https://github.com/insightsengineering/r-revdepcheck-action/pull/4
Tests:
- https://github.com/insightsengineering/teal.goshawk/actions/workflows/scheduled.yaml?query=branch%3Afix_non_cran2
=> use setup-r-deps in revdepcheck

.github/workflows/rhub.yaml
Some of the machines in Rhub fails badly when installing quarto. We need to skip it (i) during installing pre-requisites and (ii) in rhub itself. For the latter I opened an issue and the author agrees to hard-code the skip. Note it's not done ATM
=> Skip quarto install for rhub workflow

.github/workflows/bioccheck.yaml, .github/workflows/build-check-install.yaml, .github/workflows/pkgdown.yaml, .github/workflows/roxygen.yaml, .github/workflows/test-coverage.yaml
Extend parameters to support custom logic in TLG-Catalog
=> build-check-install - extend params for setup-r-depenencies

.github/workflows/build-check-install.yaml
Just a minor change in the description
=> Update description of parameters so it's clear where to look for theaction yaml

.github/workflows/build-check-install.yaml
This adds an option to disable package rebuilds and uploads for release events (aka when a tag is created).
Example sage:
```yaml
jobs:
r-cmd:
name: R CMD Check 🧬
uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
with:
disable-package-rebuild-and-upload: true
```
=> feat: Add option to disable package rebuilds and uploads

.github/workflows/build-check-install.yaml, .github/workflows/check.yaml.shared, .github/workflows/release.yaml.shared
Following https://github.com/insightsengineering/teal.reporter/issues/288 this PR add this note as a blocking note.
I added the note to several workflows (based on a [PR on other repositories](https://github.com/insightsengineering/teal.reporter/pull/291)), let me know if this is a good approach.
=> Add a blocking note for missing VignetteBuilder engine
